Fixed error handling and noise.  See https://issues.apache.org/jira/browse/RYA-54

diff --git a/extras/vagrantExample/src/main/vagrant/Vagrantfile b/extras/vagrantExample/src/main/vagrant/Vagrantfile
--- a/extras/vagrantExample/src/main/vagrant/Vagrantfile
+++ b/extras/vagrantExample/src/main/vagrant/Vagrantfile
@@ -56,7 +56,7 @@ EOF
     echo debconf shared/accepted-oracle-license-v1-1 seen true | \
       sudo /usr/bin/debconf-set-selections
     sudo apt-get install -y oracle-java8-installer
-    sudo ln -s /usr/lib/jvm/java-8-oracle/ /usr/lib/jvm/default-java
+    sudo ln --force -s /usr/lib/jvm/java-8-oracle/ /usr/lib/jvm/default-java
     
     echo "Installing Tomcat..."
     sudo apt-get install -y tomcat7
@@ -64,11 +64,14 @@ EOF
     echo "Installing Unzip..."
     apt-get install unzip
 
+    # List of dependency versions
+    ACCUMULO_VERSION=1.6.5
+
     echo "Setting up environment..."
     export JAVA_HOME=/usr/lib/jvm/java-8-oracle
-    export HADOOP_HOME=/home/vagrant/hadoop-1.2.1
-    export ZOOKEEPER_HOME=/home/vagrant/zookeeper-3.4.5-cdh4.5.0
-    export ACCUMULO_HOME=/home/vagrant/accumulo-1.6.4
+    export HADOOP_HOME=/home/vagrant/${hadoopFolder}
+    export ZOOKEEPER_HOME=/home/vagrant/${zookeeperFolder}
+    export ACCUMULO_HOME=/home/vagrant/accumulo-$ACCUMULO_VERSION
     export PATH=$PATH:$JAVA_HOME/bin:$ZOOKEEPER_HOME/bin:$ACCUMULO_HOME/bin
 
     export HADOOP_PREFIX="$HADOOP_HOME"
@@ -84,9 +87,9 @@ EOF
 
     cat >> /home/vagrant/.bashrc <<EOF
         export JAVA_HOME=/usr/lib/jvm/java-8-oracle
-        export HADOOP_HOME=/home/vagrant/hadoop-1.2.1
-        export ZOOKEEPER_HOME=/home/vagrant/zookeeper-3.4.5-cdh4.5.0
-        export ACCUMULO_HOME=/home/vagrant/accumulo-1.6.4
+        export HADOOP_HOME=/home/vagrant/${hadoopFolder}
+        export ZOOKEEPER_HOME=/home/vagrant/${zookeeperFolder}
+        export ACCUMULO_HOME=/home/vagrant/accumulo-$ACCUMULO_VERSION
         export PATH=$PATH:$JAVA_HOME/bin:$ZOOKEEPER_HOME/bin:$ACCUMULO_HOME/bin
 
         export HADOOP_PREFIX="$HADOOP_HOME"
@@ -103,31 +106,45 @@ EOF
 
     
     echo "Acquiring and Extracting ..."
-    
+    ### curl --fail causes curl to treat http status >= 400 as an error. -L follow redirects status>=300
     echo "- Hadoop"
-    curl -SL http://apache.mirrors.tds.net/hadoop/common/hadoop-1.2.1/hadoop-1.2.1.tar.gz \
-      | tar -zxC /home/vagrant
+	hadoopFolder=hadoop-1.2.1
+	hadoopUrl=http://apache.mirrors.tds.net/hadoop/common/hadoop-1.2.1/hadoop-1.2.1.tar.gz
+	if [[ ! -d $hadoopFolder ]] ; then 
+		echo "Downloading $hadoopUrl"
+		curl --silent --show-error --fail -L $hadoopUrl \
+		| tar -zxC /home/vagrant || exit 101
+	fi
 
     echo "- Zookeeper"
-    curl -SL http://archive-primary.cloudera.com/cdh4/cdh/4/zookeeper-3.4.5-cdh4.5.0.tar.gz \
-      | tar -zxC /home/vagrant
-    
+	zookeeperFolder=zookeeper-3.4.5-cdh4.5.0
+	zookeeperUrl=http://archive-primary.cloudera.com/cdh4/cdh/4/zookeeper-3.4.5-cdh4.5.0.tar.gz
+	if [[ ! -d $zookeeperFolder ]] ; then
+		echo "Downloading $zookeeperUrl"
+		curl --silent --show-error --fail -L $zookeeperUrl \
+		| tar -zxC /home/vagrant || exit 102
+    fi
+	
     echo "- Accumulo"
-    curl -SL http://apache.mirrors.pair.com/accumulo/1.6.4/accumulo-1.6.4-bin.tar.gz \
-      | tar -zxC /home/vagrant
+	accumuloUrl=http://apache.mirrors.pair.com/accumulo/$ACCUMULO_VERSION/accumulo-$ACCUMULO_VERSION-bin.tar.gz
+	if [[ ! -d ${ACCUMULO_HOME} ]] ; then
+		echo "Downloading $accumuloUrl"
+		curl --silent --show-error --fail -L $accumuloUrl \
+		| tar -zxC /home/vagrant || exit 103
+	fi
     
     echo "Configuring Zookeeper..."
-    sudo mkdir /var/zookeeper
+    sudo mkdir --parents /var/zookeeper
     sudo chown vagrant:vagrant /var/zookeeper
 
     echo "Running Zookeeper..."
-    cp zookeeper-3.4.5-cdh4.5.0/conf/zoo_sample.cfg zookeeper-3.4.5-cdh4.5.0/conf/zoo.cfg
-    sudo zookeeper-3.4.5-cdh4.5.0/bin/zkServer.sh start
+    cp ${zookeeperFolder}/conf/zoo_sample.cfg ${zookeeperFolder}/conf/zoo.cfg
+    sudo ${zookeeperFolder}/bin/zkServer.sh start
     
     echo "Configuring Accumulo..."
-    cp accumulo-1.6.4/conf/examples/1GB/standalone/* accumulo-1.6.4/conf/
-    rm accumulo-1.6.4/conf/accumulo-site.xml
-    cat >> accumulo-1.6.4/conf/accumulo-site.xml <<EOF
+    cp accumulo-$ACCUMULO_VERSION/conf/examples/1GB/standalone/* accumulo-$ACCUMULO_VERSION/conf/
+    rm --force accumulo-$ACCUMULO_VERSION/conf/accumulo-site.xml
+    cat >> accumulo-$ACCUMULO_VERSION/conf/accumulo-site.xml <<EOF
         <configuration>
             <property><name>instance.dfs.uri</name><value>file:///</value></property>
             <property><name>instance.dfs.dir</name><value>/data/accumulo</value></property>
@@ -146,26 +163,26 @@ EOF
             <property><name>tserver.compaction.major.delay</name><value>3</value></property>
             <property><name>general.classpaths</name><value>
             /data/accumulo/lib/[^.].*.jar,
-            /home/vagrant/hadoop-1.2.1/share/hadoop/common/.*.jar,
-            /home/vagrant/hadoop-1.2.1/share/hadoop/common/lib/.*.jar,
-            /home/vagrant/hadoop-1.2.1/share/hadoop/hdfs/.*.jar,
-            /home/vagrant/hadoop-1.2.1/share/hadoop/mapreduce/.*.jar,
-            /home/vagrant/hadoop-1.2.1/share/hadoop/yarn/.*.jar,
-            /home/vagrant/accumulo-1.6.4/server/target/classes/,
-            /home/vagrant/accumulo-1.6.4/lib/accumulo-server.jar,
-            /home/vagrant/accumulo-1.6.4/core/target/classes/,
-            /home/vagrant/accumulo-1.6.4/lib/accumulo-core.jar,
-            /home/vagrant/accumulo-1.6.4/start/target/classes/,
-            /home/vagrant/accumulo-1.6.4/lib/accumulo-start.jar,
-            /home/vagrant/accumulo-1.6.4/fate/target/classes/,
-            /home/vagrant/accumulo-1.6.4/lib/accumulo-fate.jar,
-            /home/vagrant/accumulo-1.6.4/proxy/target/classes/,
-            /home/vagrant/accumulo-1.6.4/lib/accumulo-proxy.jar,
-            /home/vagrant/accumulo-1.6.4/lib/[^.].*.jar,
-            /home/vagrant/zookeeper-3.4.5-cdh4.5.0/zookeeper[^.].*.jar,
+            /home/vagrant/${hadoopFolder}/share/hadoop/common/.*.jar,
+            /home/vagrant/${hadoopFolder}/share/hadoop/common/lib/.*.jar,
+            /home/vagrant/${hadoopFolder}/share/hadoop/hdfs/.*.jar,
+            /home/vagrant/${hadoopFolder}/share/hadoop/mapreduce/.*.jar,
+            /home/vagrant/${hadoopFolder}/share/hadoop/yarn/.*.jar,
+            /home/vagrant/accumulo-$ACCUMULO_VERSION/server/target/classes/,
+            /home/vagrant/accumulo-$ACCUMULO_VERSION/lib/accumulo-server.jar,
+            /home/vagrant/accumulo-$ACCUMULO_VERSION/core/target/classes/,
+            /home/vagrant/accumulo-$ACCUMULO_VERSION/lib/accumulo-core.jar,
+            /home/vagrant/accumulo-$ACCUMULO_VERSION/start/target/classes/,
+            /home/vagrant/accumulo-$ACCUMULO_VERSION/lib/accumulo-start.jar,
+            /home/vagrant/accumulo-$ACCUMULO_VERSION/fate/target/classes/,
+            /home/vagrant/accumulo-$ACCUMULO_VERSION/lib/accumulo-fate.jar,
+            /home/vagrant/accumulo-$ACCUMULO_VERSION/proxy/target/classes/,
+            /home/vagrant/accumulo-$ACCUMULO_VERSION/lib/accumulo-proxy.jar,
+            /home/vagrant/accumulo-$ACCUMULO_VERSION/lib/[^.].*.jar,
+            /home/vagrant/${zookeeperFolder}/zookeeper[^.].*.jar,
             $HADOOP_CONF_DIR,
-            /home/vagrant/hadoop-1.2.1/[^.].*.jar,
-            /home/vagrant/hadoop-1.2.1/lib/[^.].*.jar,
+            /home/vagrant/${hadoopFolder}/[^.].*.jar,
+            /home/vagrant/${hadoopFolder}/lib/[^.].*.jar,
             </value></property>
             <property><name>general.dynamic.classpaths</name><value>/data/accumulo/lib/ext/[^.].*.jar</value></property>
             <property><name>trace.port.client</name><value>0</value></property>
@@ -175,74 +192,88 @@ EOF
             <property><name>gc.port.client</name><value>0</value></property>
         </configuration>
 EOF
-    cat > accumulo-1.6.4/conf/masters <<EOF
+    cat > accumulo-$ACCUMULO_VERSION/conf/masters <<EOF
 rya-example-box
 EOF
 
-	cat > accumulo-1.6.4/conf/slaves <<EOF
+	cat > accumulo-$ACCUMULO_VERSION/conf/slaves <<EOF
 rya-example-box
 EOF
-    sudo mkdir /data
+    sudo mkdir --parents /data
     sudo chown vagrant:vagrant /data
-    mkdir /data/accumulo
-    mkdir /data/accumulo/lib
-    mkdir /data/accumulo/lib/ext
+    mkdir --parents /data/accumulo/lib/ext
 
     echo "Starting Accumulo..."
-    accumulo-1.6.4/bin/accumulo init --instance-name dev --password root
-    accumulo-1.6.4/bin/start-all.sh
+    accumulo-$ACCUMULO_VERSION/bin/accumulo init --instance-name dev --password root
+    accumulo-$ACCUMULO_VERSION/bin/start-all.sh
 
     echo 'Done!'
 
 	echo "Installing Sesame Server"
 	# creating log dir sesame-http-server-2.7.6
-	sudo mkdir -p /usr/share/tomcat7/.aduna 
+	sudo mkdir --parents /usr/share/tomcat7/.aduna 
 	sudo chown -R tomcat7:tomcat7 /usr/share/tomcat7  
-    sudo ln -s /usr/share/tomcat7/.aduna/openrdf-sesame/logs /var/log/tomcat7/openrdf-sesame
-	
-	sudo curl -O http://repo1.maven.org/maven2/org/openrdf/sesame/sesame-http-server/2.7.6/sesame-http-server-2.7.6.war
-	sudo mv sesame-http-server-2.7.6.war /var/lib/tomcat7/webapps/openrdf-sesame.war
+    sudo ln --force -s /usr/share/tomcat7/.aduna/openrdf-sesame/logs /var/log/tomcat7/openrdf-sesame
+	sesamewar=/var/lib/tomcat7/webapps/openrdf-sesame.war
+	if [[ ! -s $sesamewar ]] ; then 
+		echo "Downloading"
+		sudo curl --silent --show-error --fail -L --output $sesamewar http://repo1.maven.org/maven2/org/openrdf/sesame/sesame-http-server/2.7.6/sesame-http-server-2.7.6.war || exit 110
+	fi
 	echo "Sesame http server deployed at http://rya-example-box:8080/openrdf-sesame"
 	
 	echo "Installing Sesame Workbench"
-	sudo curl -O http://repo1.maven.org/maven2/org/openrdf/sesame/sesame-http-workbench/2.7.6/sesame-http-workbench-2.7.6.war
-	sudo mv sesame-http-workbench-2.7.6.war /var/lib/tomcat7/webapps/openrdf-workbench.war
+	workbench=/var/lib/tomcat7/webapps/openrdf-workbench.war
+	if [[ ! -s $workbench ]] ; then 
+		echo "Downloading"
+		sudo curl --silent --show-error --fail -L --output $workbench http://repo1.maven.org/maven2/org/openrdf/sesame/sesame-http-workbench/2.7.6/sesame-http-workbench-2.7.6.war || exit 111
+	fi
 	echo "Sesame workbench deployed at http://rya-example-box:8080/openrdf-workbench"
 
-	echo "Downloading Rya"
-	# Right now it's on dropbox, but eventually it'll be on maven...
-
-	sudo curl -L https://www.dropbox.com/s/7e74yiuq4jmu0od/rya.indexing.example-3.2.10-SNAPSHOT-distribution.zip?dl=0 -o rya.indexing.example-3.2.10-SNAPSHOT-distribution.zip
-	sudo mkdir rya.indexing.example-3.2.10-SNAPSHOT-distribution
-	sudo unzip rya.indexing.example-3.2.10-SNAPSHOT-distribution.zip -d rya.indexing.example-3.2.10-SNAPSHOT-distribution
+	echo "Installing Rya"
+	ryaIndexing=rya.indexing.example-3.2.10-SNAPSHOT-distribution
+	if [[ ! -s ${ryaIndexing}.zip ]] ; then
+		# Right now it's on dropbox, but eventually it'll be on maven...
+		echo "Downloading quietly..."
+		sudo curl --silent --show-error --fail -L --output ${ryaIndexing}.zip https://www.dropbox.com/s/7e74yiuq4jmu0od/${ryaIndexing}.zip?dl=0  || exit 112
+	fi
+	sudo mkdir --parents ${ryaIndexing}
+	sudo unzip -o ${ryaIndexing}.zip -d ${ryaIndexing}
 	
 	# soft linking the files doesn't seem to work in tomcat, so we copy them instead :(
-	sudo cp rya.indexing.example-3.2.10-SNAPSHOT-distribution/dist/lib/* /var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib/
-	sudo cp rya.indexing.example-3.2.10-SNAPSHOT-distribution/dist/lib/* /var/lib/tomcat7/webapps/openrdf-sesame/WEB-INF/lib/
+	sudo cp ${ryaIndexing}/dist/lib/* /var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib/
+	sudo cp ${ryaIndexing}/dist/lib/* /var/lib/tomcat7/webapps/openrdf-sesame/WEB-INF/lib/
 
 	# These are older libs that breaks tomcat 7
-	sudo rm /var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib/servlet-api-2.5.jar
-	sudo rm /var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib/jsp-api-2.1.jar
-	sudo rm /var/lib/tomcat7/webapps/openrdf-sesame/WEB-INF/lib/servlet-api-2.5.jar
-	sudo rm /var/lib/tomcat7/webapps/openrdf-sesame/WEB-INF/lib/jsp-api-2.1.jar
+	sudo rm --force /var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib/servlet-api-2.5.jar
+	sudo rm --force /var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib/jsp-api-2.1.jar
+	sudo rm --force /var/lib/tomcat7/webapps/openrdf-sesame/WEB-INF/lib/servlet-api-2.5.jar
+	sudo rm --force /var/lib/tomcat7/webapps/openrdf-sesame/WEB-INF/lib/jsp-api-2.1.jar
 	
 	sudo chown -R tomcat7:tomcat7 /var/lib/tomcat7/webapps/openrdf-workbench/WEB-INF/lib/
 	sudo chown -R tomcat7:tomcat7 /var/lib/tomcat7/webapps/openrdf-sesame/WEB-INF/lib/
 
-	# Download and install new templates for OpenRdf WorkBench
-	sudo curl -L -O https://www.dropbox.com/s/dgw63m66nubyy4z/rya.vagrant.example-3.2.10-SNAPSHOT.jar
-	sudo mkdir rya.vagrant.example-3.2.10-SNAPSHOT
-	sudo unzip rya.vagrant.example-3.2.10-SNAPSHOT.jar -d rya.vagrant.example-3.2.10-SNAPSHOT
-	sudo cp rya.vagrant.example-3.2.10-SNAPSHOT/*.xsl /var/lib/tomcat7/webapps/openrdf-workbench/transformations/
+	echo "Downloading and installing new templates for OpenRdf WorkBench"
+	ryaVagrant=rya.vagrant.example-3.2.10-SNAPSHOT
+	if [[ ! -s ${ryaVagrant}.jar ]] ; then
+		echo "Downloading"
+		sudo curl --silent --show-error --fail -L -O https://www.dropbox.com/s/dgw63m66nubyy4z/${ryaVagrant}.jar || exit 120
+	fi
+	sudo mkdir --parents ${ryaVagrant}
+	sudo unzip -o ${ryaVagrant}.jar -d ${ryaVagrant}
+	sudo cp ${ryaVagrant}/*.xsl /var/lib/tomcat7/webapps/openrdf-workbench/transformations/
 	
 	echo "Deploying Rya Web"
-	sudo curl -L https://www.dropbox.com/s/332wr4b2f34dp6e/web.rya-3.2.10-SNAPSHOT.war?dl=0 -o web.rya.war
-	sudo cp web.rya.war /var/lib/tomcat7/webapps/web.rya.war
+	ryaWar=web.rya-3.2.10-SNAPSHOT.war
+	if [[ ! -s ${ryaWar} ]] ; then
+		echo "Downloading"
+		sudo curl --silent --show-error --fail -L https://www.dropbox.com/s/332wr4b2f34dp6e/${ryaWar}?dl=0 --output ${ryaWar} || exit 121
+	fi
+	sudo cp ${ryaWar} /var/lib/tomcat7/webapps/web.rya.war
 	# Wait for the war to deploy
 	sudo sleep 10
 	# These are older libs that breaks tomcat 7
-	sudo rm /var/lib/tomcat7/webapps/web.rya/WEB-INF/lib/servlet-api-2.5*.jar
-	sudo rm /var/lib/tomcat7/webapps/web.rya/WEB-INF/lib/jsp-api-2.1.jar
+	sudo rm --force /var/lib/tomcat7/webapps/web.rya/WEB-INF/lib/servlet-api-2.5*.jar
+	sudo rm --force /var/lib/tomcat7/webapps/web.rya/WEB-INF/lib/jsp-api-2.1.jar
 
 	echo "Modify Rya Web Config"
 	cat > /var/lib/tomcat7/webapps/web.rya/WEB-INF/classes/environment.properties <<EOF
@@ -258,9 +289,6 @@ EOF
 	
 	# restart tomcat
 	sudo service tomcat7 restart
-	
-
-
 	
 	
   SHELL
